author: DerFlash
database: true
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.derflash.plugins.eggroulette.CNEggRoulette
name: CNEggRoulette
startup: postworld
url: http://www.cube-nation.de/
version: '1.1'
commands:
    egg:
        description: Manage eggroulette